appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EfFoJcgZcTYpGLHudvpRX3ppnKSANPEF6Z2bycXieQzvoM2XoGEmRsEvF/6FIiEYofu7nInq3ZvkvYrjzR64fSOYmHx5YcTVHEw9Gz5s++XNfSk34PFOpBuhq3kxrlTA96+wTJ6QiRlYH7JDQiufXUaosuuUagIpAjmhhqXRcRQv26qohwjerstC8KxOowqgBqhwTuM9Nwz+zlPv3tCuOZP6x9Rm0sv7O0u7fk+VYLBASkZSh+ehpBgLpGIqw9kyGgBVIDXMzoS+U9LyQX8PbUMD19ybyeVaqzxgrrrxU8DWaxrlEJ2ovwIcwbuvcT7isbw3PN5GsqpyL89pexujhIhbf57aSBAxGcXacCJkV3t1L8ndS0la8avtlzh/5jtAlnoA8wLangUPRf3P/UYDLMjgwLI8/yOhx8nlZmL/vhgffcCWpIgQpGp+4BNl3sIzdg6N3dahT92ENUL/d/3xNc2lZbb/wV1+cSHggghjxW0Sp/ZiH90IdM9RwL63Tyy5N8/YdUjscWQC3+pTNepwDYUSyNygC36aSI5ZKbz7qvxDw5TeHTTF7veBNkl4BrsnP1eJLWVuHtJF3JB/r/jVGLBR5OVvhtFeoG9k/+aEF3EiH4pmew8qWG+eYsfD8TXnDZvBOFVAqmwHoh3RgGu3gFi04z0O9D4WU56+Y0vez14=}
