travis:
  secure:
    BINSTAR_TOKEN: jfbeDz+8OnlwNWTsmNvmb5iXKfkYBuRWDg2AsLgCw3A8ydpF2m+RAiAzTCHZUCY8VxaQK9L5R9UodolMqHDDmWeJlOtLsS7zhHu4MnQKdNMTCPwGIL5Mnk3ICu1VTbx/ze2OpUrRSqKKNb6nFViBCBjgUQVMv18m+/QJZCrSK5SK4T6OghDacvW27IEZG4PuthxW5mHp3RF+eB2yTVBQy1/kxgTo69U6L7wLPMyAUhCfi9Y8Pm/ZEuOCJFahORvZzFmuBwU6rt2LZ5F39Bno9wqP8M2oenSKsrxWPylCSHRApSmU+QiM4bXy7CWQVnDp6QYNybt9egKCOx3YFIxslzlze27yKt5ocn7YiIOcguHiL7SxLU0cYoRdEIJjmEudFqBmCqkbuf6XEM/VxFMQW1qRtWuIqlHs/BqQRrveIUc6afPRGjUmvLPLXckv1fPfhJEy37mdm65W8g/uEka+HT4wAXTPS3b7CPbkJ1L2lo8KmNoYmjZdM/wn/2CUIrp0AmAahxM6YXQ0Aol9+mA7uTpLaHMhXeh+x4mbs6CBJNzukOoRdFgKjDJGPBsqa24zI87c3rW++4ynaaKBn/W9ZwjoP7WXMd5naXkM2Lj8s8sN7JqqKaP7xSKWm5Eaffv0Dn0Ug0odrqMXl8tPgXm003mVPc+h9RXJM2mtDZXfm7E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
